### ISSUE TITLE
[Feature] Plans for revamping the ECS design to use value objects

### ISSUE THREAD

**Issue by ilumar589** [AlmasB/FXGL#1309]
Hi,

   First of all, congratulations on this great framework. It's elegantly designed and a pleasure to work with. Back to the title at hand, I'm curios if there are any long term plans to use value objects when they eventually arrive in Java for more memory efficient components. As it is right now it would be impossible to create a record/value object as pure data component because it has to extend the abstract class Component and that is a restriction for record/value objects. Also, I have not looked into the current ECS implementation but this would also eliminate the need for object pooling for intensive games. This is kind of a tangent but just as an idea if we remove the behavior part from components and do that in system function it opens up more opportunities to do multithreaded code/ordering/sync of systems that operate on component combinations . Sorry for the rant and thanks in advance! Have a nice day!

**Comment by AlmasB** [comment]
Hi, @ilumar589 

Thanks for the idea. The answer is yes, it's interesting, but no plans at the moment. Whilst it would be quite interesting to explore value objects for ECS, the current EC (without S) model is a result of many iterations that addresses the majority of use cases. Therefore, the value objects based ECS (if developed in the future) will probably be a separate feature that integrates into the current model, rather than replacing the existing EC model.
