### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by pierredavidbelanger** [AlmasB/FXGL#217]
I do not understand [this mulLocal](https://github.com/AlmasB/FXGL/blob/master/src/main/java/com/almasb/fxgl/physics/PhysicsComponent.java#L113) and [this mul](https://github.com/AlmasB/FXGL/blob/master/src/main/java/com/almasb/fxgl/physics/PhysicsComponent.java#L150) since the [PhysicsWorld class](https://github.com/AlmasB/FXGL/blob/master/src/main/java/com/almasb/fxgl/physics/PhysicsWorld.java#L580) is supposed to take care of this.

**Comment by AlmasB** [comment]
I've just run history search and it seems it's been there since day 1 of supported physics. I seem to vaguely remember that I wanted the meter based velocity and pixel based velocity to be of similar values from the outside.

Now that I think about it, it doesn't make sense, so spot on for noticing it :+1: it's removed in the next version, [commit](https://github.com/AlmasB/FXGL/commit/9e9088d142b7e556888cdf2b303369cd88f1afb1)

**Comment by pierredavidbelanger** [comment]
Oh, that was fast!
Thank you for this great lib !!
