### ISSUE TITLE
Help Wanted: Wiki

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#289]
There are several sections in the Wiki that have not been written up yet. Any help with these sections (or your ideas) are greatly appreciated

**Comment by hauptDev** [comment]
I've translated the introduction into german with some slightly modifications. Just had to share it as txt-file, because .md files aren't allowed so you've to change it. If you want, you can add me as contributor. Would like to support the project even more but I'm just a hobby programmer with basic skills. 
[German.txt](https://github.com/AlmasB/FXGL/files/1179551/German.txt)

Regards,
[Konstantin Haupt](https://github.com/hauptDev) [:email:](mailto:hauptdev@posteo.de)

**Comment by AlmasB** [comment]
Awesome, thanks for this. The page has been added to [German translation](https://github.com/AlmasB/FXGL/wiki/German) with the link to your account. You are very welcome to contribute more. Let me know what you'd like to do

**Comment by jacekpoz** [comment]
Hey, I also translated the introduction to Polish. I'm in the process of translating the whole wiki to Polish, but that'll definitely take time. I'll post some updates here when I translate more. Here's the translation: 
[Polish.txt](https://github.com/AlmasB/FXGL/files/5440870/FXGL.11.Wstep.txt)

**Comment by AlmasB** [comment]
cool, many thanks

**Comment by AlmasB** [comment]
Specific pages that need help with updating have been identified and extracted into issues: #981, #982, #983, #984
