### ISSUE TITLE
Help Wanted: Design FXGL Editor

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#362]
- [ ] Software design (how the editor integrates with FXGL)
- [ ] Functionality (what the editor can do)
- [ ] Visual design (what the editor looks like)

- [ ] Ability to change settings (e.g. physics properties) real-time with sliders and other UI elements

**Comment by AlmasB** [comment]
The workflow seems to converge to: use Tiled to build base level data, then load (.tmx / .json) into the FXGL editor and generate EntityFactory, then run the game from any IDE.

**Comment by bturner1273** [comment]
**HitBox GUI-**

This GUI could have a box, circle, and chain tool (the chain tool would basically just plotting points to be connected), much like a pen tool they would be used to draw over the game graphics but the drawing would correlate to a hitbox component on that (desired) entity type. It could be implemented in the CTRL+0 menu where the hitbox view toggle is and would make a much easier/visual way to implement hitboxes. This could be paired with a scaling tool so that the proper geometry and anchoring of the hitbox is maintained upon scaling.

**Comment by AlmasB** [comment]
Initial functionality has been designed and described as #999 #1000 #1001 This issue is merged into them
