### ISSUE TITLE
FXGL nested inside JavaFX GUI

### ISSUE THREAD

**Issue by JeffThe** [AlmasB/FXGL#433]
Hi,

is there any possibility to nest FXGL inside JavaFX GUI, like for example canvas?

**Comment by AlmasB** [comment]
Hi, what do you mean by that?

**Comment by JeffThe** [comment]
Something like that : [https://ibb.co/e4aMdR](url)

**Comment by AlmasB** [comment]
**Short answer, no**. FXGL is a framework, so you build your app _within_ FXGL, rather than _use_ it.

**Long answer, yes,** but it's against the design and so you'll probably be fighting through the API. You can write a bridge between your app and FXGL. That bridge is going to start and run FXGL. You will then hook your app to the bridge app to be able to access FXGL and its features, though some will probably be unavailable.
