### ISSUE TITLE
Entities un-pushable? 

### ISSUE THREAD

**Issue by Thom9521** [AlmasB/FXGL#464]
Hi. Is it possible to make entities unpushable?
My player pushes my enemies when he hits them and i don't want that to happen. 😃

**Comment by AlmasB** [comment]
FXGL uses [box2d](http://box2d.org/) as the simulation engine. Please refer to their documentation. My guess is that you might be able to set some collision flags, so that player doesn't physically collide with enemies, yet collision events are reported still. I don't know if this is possible via FXGL API, but maybe via box2d API.

If you find out how to do this with box2d and if this isn't possible with current FXGL API, I'm happy to open an issue for it.
