### ISSUE TITLE
Little qestion

### ISSUE THREAD

**Issue by Risa123** [AlmasB/FXGL#584]
Why are you using both java and kotlin ?

**Comment by AlmasB** [comment]
Hi,

The project started with pure Java, I wasn't aware of Kotlin's existence back then. Over the years I've moved the core parts to Kotlin, with most of the new code being written in Kotlin.

Certain parts are kept in Java intentionally. For example with interfaces in Java, both Java and Kotlin can understand the functional approach, which cannot work the other way around by design.
