### ISSUE TITLE
Custom scene into custom Stage

### ISSUE THREAD

**Issue by Levvy055** [AlmasB/FXGL#611]
GameApplication creates own stage with own startupScene.
It will be nice to make it placable into existing custom scene.
Let's say I have my app in the root of BorderPane and I want to put GameApplication into center Node.
Is it possible?

**Comment by AlmasB** [comment]
As long as your starting class `extends GameApplication` you should be able to get the root of the FXGL `Scene` object and use it as needed.

If the application starts as a normal JavaFX app, i.e. `extends Application`, my intuition is that it will not run as intended.

**Comment by Levvy055** [comment]
Error during launch:
```
java.lang.IllegalStateException: Application launch must not be called more than once
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:175)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:156)
	at javafx.graphics/javafx.application.Application.launch(Application.java:296)
	at fxgl.all/com.almasb.fxgl.app.GameApplication$FXGLApplication.launchFX(GameApplication.java:210)
```

**Comment by Levvy055** [comment]
It will be nice to override FXGLApplication which overrides Application, but Engine class is internal unfortunately

**Comment by AlmasB** [comment]
I will have a think about what the architecture might look like and see if I can implement it before next release

**Comment by AlmasB** [comment]
@Levvy055 Using the latest build `dev-SNAPSHOT`, you have the option to do the following:

```
    @Override
    public void start(Stage stage) throws Exception {

        Stage stage1 = new Stage();

        GameApplication.customLaunch(new MyGame(), stage1);
    }

```

In other words, you can have a normal JavaFX application and then create a new undecorated Stage to "embed" into your own (this isn't actually embedding we are simply hiding the fact that there are two windows). See [example code](https://github.com/AlmasB/FXGL/blob/dev/fxgl-samples/src/main/java/sandbox/FXApp.java) and [what it looks like](https://twitter.com/AlmasBaim/status/1122095757828546560)

If you are only interested in a single (game) root of FXGL scene, then you can embed that into the center of your BorderPane. However, as soon as you start switching FXGL scenes, e.g. game -> game menu, this solution will break since there are multiple roots in FXGL. Hence, the above workaround with an undecorated Stage.
