### ISSUE TITLE
are animated textures available in FXGL 11 beta?

### ISSUE THREAD

**Issue by bturner1273** [AlmasB/FXGL#613]
`@Spawns("FlappyBird")

	public Entity newFlappyBird(SpawnData data) {

		AnimationChannel fly_channel = new AnimationChannel(
				getAssetLoader().loadImage("FlappyBird/flappy_fly_sheet.png"),
				3, 102/3, 24,
				Duration.millis(250),
				0, 2);	
	
		AnimatedTexture fly = new AnimatedTexture(fly_channel);

		return entityBuilder()
				.from(data)
				.view(fly)
				.build();

	}`

tried this^^ didn't work. Do I need to use animationBuilder() in some capacity?

**Comment by AlmasB** [comment]
They work slightly differently in 11.0+. There are two modes: play and loop. If your texture is supposed to loop in that animation, then the following should do the trick.

```
AnimatedTexture fly = new AnimatedTexture(fly_channel);

fly.loop();

return entityBuilder()
			.from(data)
			.view(fly)
			.build();
```

Also see [this example](https://github.com/AlmasB/FXGLGames/blob/master/Mario/src/main/java/com/almasb/fxglgames/mario/PlayerComponent.java) 

Please let me know if this works, because if not I will need to fix it

**Comment by bturner1273** [comment]
works perfect just needed animated_texture_name.loop()

**Comment by AlmasB** [comment]
Also, for convenience if your entire texture (image) is just a single animation channel, then it could be shortened to:

```
return entityBuilder()
	.from(data)
	.view(texture("FlappyBird/flappy_fly_sheet.png").toAnimatedTexture(3, Duration.millis(250)))
	.build();

```
