### ISSUE TITLE
Expose scale properties of GameScene

### ISSUE THREAD

**Issue by SKeeneCode** [AlmasB/FXGL#624]
Currently accessing the scale Properties of the GameScene requires:

`Scale scale = (Scale) getGameScene().getRoot().getTransforms().get(0);`

Requesting that these properties be exposed to ease the process should a user wish to access/bind them.

**Comment by AlmasB** [comment]
Scale X and Y are stored in MainWindow.kt (`scaleRatioX` and `scaleRatioY`). Possible extension is to have these properties in Settings.kt and bind to them instead. This way the properties are (consistent with current API) accessed through `FXGL.getSettings()`. One interesting side-effect from this would be that users can directly scale their game if they wanted to

**Comment by AahzBrut** [comment]
Curent implementation of MainWindow has scaleRatio calculated:
`        scaleRatioX.set(scaledWidth.value / settings.width)`
`        scaleRatioY.set(scaledHeight.value / settings.height)`

so the primary scale attributes are `scaledWidth` and `scaledHeight `

the question is - move to Settings scaleRatio (and change the logic of scaling in MainWindow) or scaledWidth/scaledHeight?

**Comment by AlmasB** [comment]
hmm, good point, I'll have a think about it and update the issue as needed. Along the same lines I am also considering an option that would prevent auto-scaling. Primary use case for that being apps like editors, where one would want to make use of all available space, rather than maintain consistency across all displays.
