### ISSUE TITLE
Bug: Repeated event does not always end correctly.

### ISSUE THREAD

**Issue by marvinbuff** [AlmasB/FXGL#666]
### Bug Description
I encountered inconsistent behaviour regarding those few lines.  

![image](https://user-images.githubusercontent.com/9862282/64977630-120c0000-d8b4-11e9-87c3-dd0c4ae9f61e.png)

I would expect that given `enemiesToSpawn = 1` it would exactly execute ones. Unfortunately, seemingly randomly it will spawn infinite amount of enemies. 

#### Behaviour
Step 1: I run the code and everything works fine.
Step 2: I change unrelated code and suddenly instead of once, it is executed infinite times.
Step 3: I stop the execution and rerun, it works now without changing any line of code. 

#### Importance
This issue is not critical to me and might be hard to fix without reproducible example. I will add more information if I see a pattern or get a consistent case.

**Comment by AlmasB** [comment]
Thanks for this. Can you please also post `spawnEnemy` function?

**Comment by AlmasB** [comment]
In addition, if you explain your use case, perhaps we can find a more suitable solution altogether?

**Comment by marvinbuff** [comment]
Thanks for taking the time. As for the use case, I only happened three times yet and I was not able to deduce a cause. I just know that either `enemiesLeft` does not update to false, although the `enemiesToSpawn` variable is negative, or that `runAtIntervalWhile` function is not informed about the change of `enemiesLeft`.

![image](https://user-images.githubusercontent.com/9862282/64979993-3ae2c400-d8b9-11e9-9919-3664f7638ddd.png)

![image](https://user-images.githubusercontent.com/9862282/64980028-4cc46700-d8b9-11e9-9707-bcc235b09f3b.png)

**Comment by AlmasB** [comment]
I think I get what you are trying to do: spawn enemies every second until all of them are spawned. So I assume `enemiesToSpawn > 0` when the game starts, otherwise the timer won't run at all. Is it possible that the `enemiesLeft` is garbage collected? That would explain the erratic behaviour. Please can you move `enemiesLeft` to an instance-level variable and then run the game?

**Comment by marvinbuff** [comment]
Exactly, it is pretty much copy pasted from your tower defense example. Garbage collector would explain the inconsistent behaviour very good.
However, not sure if that is possible. 
- `enemiesLeft` is a `SimpleBooleanProperty` which is in the scope of initGame
- then I give it as argument for `runAtIntervalWhile`, this creates a `TimerAction` which is stored in `timerActions` and is added as listener to `enemiesLeft`. Therefore there is a hard link chain which should prevent collecting. Right? 

The next time it occurs I try to get more information and experiment with making `enemiesLeft` an instance-level variable.

**Comment by AlmasB** [comment]
When `initGame()` completes, `enemiesLeft` ref goes out of scope, whilst no reference in `run...` is retained, so it is feasible that it gets GC'ed.

**Comment by marvinbuff** [comment]
So, a little update. I managed to create a reproducible example by calling the garbage collector. And as you predicted, the issue resolves itself when I move the `enemiesLeft` declaration to the instance scope. 

However, I still do not understand why adding a listener to `enemiesLeft` does not create a hard-reference between the two objects and prevent collection. 

Anyway, I guess this was more an implementation error of mine and no bug. Thanks for the help.

**Comment by AlmasB** [comment]
@marvinbuff I've had a quick look at the implementation of listeners. You are correct that a hard reference is created but it is circular:

```
Property (object) -> ExpressionHelper (SingleInvalidation) -> Property (object)
```

After `initGame()` is finished, the last reachable reference to `object` is lost. The reference kept by `ExpressionHelper` is not reachable since the only way to reach `ExpressionHelper` is via `object`. So it makes sense that `object` is eligible for GC.

I'll keep the issue open until I add a note in the documentation of `runAtIntervalWhile`; you are welcome to contribute that as well if you want.
