### ISSUE TITLE
Add setWidthFromRatio and setHeightFromRatio to Settings

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#669]
Example usage: (when width or height is known and the other aspect needs to be set using a specific ratio)

```
settings.setWidth(800);
settings.setHeightFromRatio(16 / 9);
```

**Comment by shubhankarb180** [comment]
Can I know more about the issue ?

**Comment by AlmasB** [comment]
Sure, `Settings.kt` needs to be updated to have two new functions named above. The idea is that the width (or height) is set by user and they want to set the other aspect (height or width) using some ratio, such as 16 / 9, so the function:

```
setHeightFromRatio( ratio ) {
    height = ... calculated based on width
}

same for setWidthFromRatio ...
``

**Comment by shubhankarb180** [comment]
I don't know much about kotlin, but I know how to create a function. So could you guide me where exactly I need to place the function?

**Comment by AlmasB** [comment]
[Here](https://github.com/AlmasB/FXGL/blob/dev/fxgl/src/main/kotlin/com/almasb/fxgl/app/Settings.kt#L238), just above the `toReadOnly` func

**Comment by nandhae** [comment]
I'd like to pick this if it's still up for grabs.

**Comment by AlmasB** [comment]
I think maybe @shubhankarb180 is already working it? If not, feel free to add this.

**Comment by nandhae** [comment]
@AlmasB Sure, Thanks. @shubhankarb180 Let me know here if you are not working on it and want me to pick this up.

**Comment by shubhankarb180** [comment]
@nandhae You can work too. I was not able to add as I don't know much kotlin.

**Comment by nandhae** [comment]
@AlmasB Raised a PR with two simple functions which takes ratio as a fraction. The clarifications i would be needing are,
1. Assumed that ratio would be fraction and did not try to read as string. Eg: "16:9". Please verify if this is okay.
2. Rounded result height and width to int. Worried if it will have precision errors.
3. Could not add unit tests, since I could not access these methods in "GameSettingsTest"

Any suggestions or directions on these points would help. Would be happy to refactor and enhance.
