### ISSUE TITLE
Consider using `@NonNull` and `@Nullable` annotations in public API

### ISSUE THREAD

**Issue by dector** [AlmasB/FXGL#739]
This will improve static analysis and will make library more comfortable to use from Kotlin.

**Comment by AlmasB** [comment]
Hi, I had given it some thought initially. However, by design, there is no public API that returns or accepts `null` (if there is, it should be fixed). So the annotations would just add extra noise.

For Kotlin end-users, there are function wrappers in `FXGLForKt.kt`. Whilst it doesn't cover all public API, it is the main API "hub".

**Comment by dector** [comment]
Yup, it makes sense. But by-default IDEA suggests that all un-annotated Java parameters and functions are nullable and it's a bit annoying to fix it manually.

There is alternative solution, though: [external annotations](https://www.jetbrains.com/help/idea/external-annotations.html).

**Comment by AlmasB** [comment]
Merged into issue #677
