### ISSUE TITLE
Enable showing Entities over UI components

### ISSUE THREAD

**Issue by marvinbuff** [AlmasB/FXGL#768]
### Description
The use case I have is that I have UI elements which should be shown underneath game elements. Looking at the impelmentation, the uiRoot is strictly painted over the gameRoot. My question is now if I should change my architecture to accustom that, and if yes how, or if we can enable this functionality so it works for me. 

The specific use case is that I create these buttons on the left using FXML, which when pressed give a dragged tower which then can be placed on the board. Unfortunately, the dragged tower is only showed when exiting the UI components. Moreover, I also have a second use case where I want to have some kind of slider which is initialized by FXML and then the invaders are shown there with a time stamp to foresee the incoming enemies.
![image](https://user-images.githubusercontent.com/9862282/76681450-190d9400-65f3-11ea-8a36-bf43527af405.png)

**Comment by AlmasB** [comment]
Yes, UI layer is always on top of game layer, by design, so it is unlikely to change.

Going with the design you have now, I would make the background of the UI semi-transparent. This should help a bit with the current use case.

Another approach is to change the gameplay design, which is something you may or may not wish to consider. The design that comes to mind is [Van Helsing's tower defense](https://www.youtube.com/watch?v=9vwAUvJi1MU). Have certain base points (structures) in the game where you can build the towers. By clicking on such a structure, a circular context menu opens that allows the user to select the towers to place.

**Comment by AlmasB** [comment]
As for the 2nd use case with the slider, if I understand correctly, isn't it just an image of the invaders that you need? If so, just use images as normal in the UI, no need to use an Entity.

**Comment by AlmasB** [comment]
Finally, you can treat UI as an Entity, thus moving everything into the game layer. In this case, the z-index of each entity will decide the drawing order. This might actually be what you are looking for...

**Comment by marvinbuff** [comment]
Thanks for the various approaches. I guess that answers my question.
Not yet sure which direction I want to go, but adding UI nodes as a view to the entity seems the most appropriate.

**Comment by marvinbuff** [comment]
The solution which works the best for me seems to be to just load the whole UI into the game root instead of the ui root. 
```
val ui = getAssetLoader().loadUI("GameView.fxml", controller)
getGameScene().addGameView(GameView(ui.root, UI_Z_LEVEL))
```

**Comment by AlmasB** [comment]
Great, thanks for letting me know
