### ISSUE TITLE
Hitbox size

### ISSUE THREAD

**Issue by computerfr33k** [AlmasB/FXGL#83]
Is it possible to make the hitbox smaller than the actual entity so that it doesn't register collision if the entities are just slightly touching.

Mainly because I am trying to make a grid based game and need to collision to only register when the next move results in collision and not when the two are only touching because they are on an adjacent cell.

I've been trying to figure out a way, but can't seem to make it work.

**Comment by AlmasB** [comment]
Since 0.1.7 you can disable auto generation of hit box from view and define your own.
entity.setGenerateHitBoxesFromView(false);

So if your grid size is 40x40, you can do something like this
entity.addHItBox(new HitBox("Body", new BoundingBox(1, 1, 38, 38));
which will make hit box smaller by 1 pixel from either side

See if this or something along those lines works for you

**Comment by computerfr33k** [comment]
Thanks, I think the reason it wasn't working for me before even when I tried to add the hitbox manually was because I didn't know that I had to set it to false for generating the hitbox from View. I assumed that it was false for some reason. But thinking about it makes sense that it would be on by default.

**Comment by computerfr33k** [comment]
Is there a way to force an entity to be drawn over the reset of the entities, such as the player will always be drawn on the top as far as entities go. Because When I remove and entity and replace it with a new one, those are then drawn over the character if it goes over the spot where the new ones were drawn.

**Comment by bsil78** [comment]
Hi,

here is my first intercourse with you about FXGL.

A commun way to manage your kind of problem is to use layers.
Here you could use a layer for background, another for background
decorations, another for bad guys, another for bullets, another for player,
and a last one for effects.

I follow FXGL improvements with attention but I am not sure if it is
implemented in FXGL.

By there you can use groups on top nodes as layers and attach your entities
to these.

Hopping it can help you.

Best regards,
Benoît

**Comment by AlmasB** [comment]
Hi, 
yes, even though it is rather messy at the moment. Instead of entity.setSceneView(...), create
EntityView view = new EntityView(entity);
view.addNode(your graphics for entity);
view.translateXProperty().bind(entity.xProperty()); // so that view moves with entity seamlessly
view.translateYProperty().bind(entity.yProperty());
view.setRenderLayer(new RenderLayer() {
    public String name() { return "PLAYER";}
    public int index() {return some int value;}
});

getGameScene().addGameView(view);

The render layer index decides at which layer your view will be drawn. By default all views have Integer.MAX_VALUE, so drawn on top of everything. So, you need to set a different render layer to all your views except the character.

Apologies for "messy" workaround, I had an entity and its view as a single object previously but when I started modularizing the codebase, I forgot about a few things, render layers being one of them.

P.S. please avoid commenting about things unrelated to the issue, especially if issue is closed. Feel free to open new issues or If you have further questions, feel free to contact me directly at almaslvl@gmail.com.
