### ISSUE TITLE
3D games with FXyz

### ISSUE THREAD

**Issue by travisfw** [AlmasB/FXGL#901]
As a JavaFX developer with interest in both games, and 3D, and also 3D games, I have been following both FXGL and [FXyz](https://github.com/FXyz/FXyz ) for a while. It would make my day to see the two projects work together.

I know there are reasons why FXGL hasn't gone 3D. I know that game development is not a goal for FXyz. Still, I think my hope may have a place on the web, and that would be right here.

**Comment by AlmasB** [comment]
Recently 3D supported for FXGL has been one of the most talked about features in the community. Whilst it is not a short-term goal, I think it would be good to have FXGL open for the possibility of 3D in the future.

Re: FXyz, I agree it would be a good start for any JavaFX 3D concepts. I have been a co-maintainer of FXyz for some time and had a chance to read through a lot of its codebase. If FXGL-FXyz integration is to take place, it's likely that a subset of FXyz might be merged into FXGL, similar to how other frameworks were integrated and adapted, e.g. jbox2d, gdxAI.

This issue is a good place for all 3D related discussions to take place.

**Comment by sproket** [comment]
This sound like an amazing idea.

**Comment by jjenkov** [comment]
Without completely knowing the internal design of FXGL - I have a suggestion. Maybe it's stupid - but then you just ignore it - or explain to me why it's stupid :-)

Would it be possible to separate game objects from their renderer? That way, you could choose to have either a 2D renderer or a 3D renderer for a given game object - or a complete game level? Or will that design not work internally?

Maybe the whole FXGL engine could be a 3D engine internally instead of a 2D engine - where 2D games were simply composed of flat polygons (Z depth 1) with the same Z position (Z position 0)  ? Could that work?

**Comment by lanthale** [comment]
There is already a good 3D Game engine in java called JMonkey. This uses actually jogl for rendering but the engine is very modular so that it should be possible to use the quantum renderer as well. 
3D is not a small undertaking...

**Comment by ilyriadz** [comment]
I try javafx with jbullet i have litle experience with it i have to deal with jbullet bugs and this is not my goal, but is very powerful.
If you want a 3d open source physic engine is the  best.
I stopped use it and return to jbox2d because is complicated for me alone.

**Comment by AlmasB** [comment]
@jjenkov With current architecture, game objects (entities) are already separated from their renderer (`ViewComponent`). So what you are suggesting actually makes a lot of sense. Plus, `TransformComponent` already supports Z, but makes use of it for z-ordering in the scene graph, rather than depth. So, yes potentially we could use the same Z for 3D, just change semantics...

@lanthale Yes jMonkey is great for 3D, but FXGL 3D need not compete with it. We could provide a higher-level access to 3D, similar to how JavaFX does it. Luckily, JavaFX already has a 3D pipeline, so the task, whilst still complex, is simpler than building a graphics engine from scratch.

@ilyriadz I believe, jMonkey uses jbullet for 3d physics. As @lanthale suggested, I wonder if we can just depend on one of the jMonkey physics modules.

**Comment by AlmasB** [comment]
Update:

The roadmap for 3D is now clearer.

- [x] Phase 1: Introduce boilerplate and make FXGL understand what 3D is.
- [x] Phase 2: Introduce custom 3D shapes to work seamlessly with FXGL architecture as views for entities, using FXyz shapes as reference for formulae
- [x] Phase 3: Introduce `.obj` format loader, building on infrastructure from Phase 2.

**Comment by AlmasB** [comment]
Update: 

Phase 2 complete. [Video demo with results](https://twitter.com/AlmasBaim/status/1378055348116979712).

**Comment by AlmasB** [comment]
Update:

[First 3D game demo tutorial](https://youtu.be/qGgLHvsIRds)

**Comment by sproket** [comment]
Very nice! Looking forward to a FPS! ;)

**Comment by AlmasB** [comment]
Update:

Initial tests with the FPS camera API: [WolFX](https://github.com/AlmasB/WolFX) demo

**Comment by sproket** [comment]
That's awesome how little code is required! I'm trying to figure out how to adjust mouse sensitivity.

**Comment by AlmasB** [comment]
settings.setMouseSensitivity

**Comment by AlmasB** [comment]
Update:

Phase 3 is almost complete with the implementation of the .obj loader, [video demo](https://twitter.com/AlmasBaim/status/1388172445891313667)

**Comment by AlmasB** [comment]
The phases of the roadmap for basic 3D support have now been completed. There are various examples under `fxgl-samples`, including the demos above that provide information on how to use 3D in FXGL.

There are still outstanding issues related to 3D collision detection and transformations. Furthermore, we lack some of the functionality that FXyz supports, such as 3D text and texture manipulations. However, these will be addressed in their separate issues, on the basis of demand.

This issue is considered resolved.
