### ISSUE TITLE
TransformComponent needs positionOriginZ

### ISSUE THREAD

**Issue by AlmasB** [AlmasB/FXGL#923]
To be consistent with existing API for 2D, we also need this for Z. Once this is implemented, ViewComponent needs to bind translateZ as below:

```
        viewRoot.translateXProperty().bind(entity.xProperty().subtract(entity.transformComponent.positionOriginXProperty()))
        viewRoot.translateYProperty().bind(entity.yProperty().subtract(entity.transformComponent.positionOriginYProperty()))
```

Currently it's just:

```
viewRoot.translateZProperty().bind(entity.transformComponent.zProperty())
```

See how positionOriginX and Y are implemented and then match the implementation

**Comment by AlmasB** [comment]
Hi, sure. The files Transform and View components are in fxgl-entity module
under kotlin sources.

**Comment by VasilisAndritsoudis** [comment]
@AlmasB Great, I will give it a shot and update you soon.

**Comment by VasilisAndritsoudis** [comment]
@AlmasB I have one question, how can I make it so that when I make changes to my fork of the repo, they take effect in development? I am guessing I have to change the dependency in the pom.xml file, however I do not know how. It would be great if you told me how to do it.

**Comment by AlmasB** [comment]
Sorry I'm not sure what you are asking. All modules depend on the development version of FXGL (i.e. the one we are editing in IDE). You can find 3D examples under fxgl-samples / ... / sandbox/test3d.

**Comment by VasilisAndritsoudis** [comment]
@AlmasB I believe I have finished with the task however I am not entirely sure on how to test it. 

At this point I have made the requested changes in the Transform and View components, built the artifacts into a jar file which I have included into a test project. There I have run both 3D examples you have supplied along with some changes I have made and it seems to be working fine.

If there is another way in which I can test feel free to inform me or else I can submit a pull request in order to complete the task.

**Comment by AlmasB** [comment]
Sounds good. Feel free to send the PR, the tests will kick in
automatically. We'll go from there

**Comment by VasilisAndritsoudis** [comment]
@AlmasB Alright I sent the PR, most of the tests run fine except 2 (the one is the JDK run on MacOS which I doubt is from the changes I made and the other is the codecov/project).
I am awaiting a response on how to proceed from here.

**Comment by AlmasB** [comment]
Many thanks, I'll take a look later today
